{% set name = "aiohttp-sse-client" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5004e29271624af586158dc7166cb0687a7a5997aab5b808f4b53400e1b72e3b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - aiohttp >=3
    - attrs
    - multidict
    - yarl

test:
  requires:
    - python {{ python_min }}
  imports:
    - aiohttp_sse_client

about:
  home: https://github.com/rtfol/aiohttp-sse-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Server-Sent Event python client library base on aiohttp
  description: |
    Server-Sent Event python client library base on aiohttp
  dev_url: https://github.com/rtfol/aiohttp-sse-client
  doc_url: https://aiohttp-sse-client.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - timkpaine
